update yaml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -106,6 +106,45 @@ jobs:
           TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           TF_VAR_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
+      - name: Run user_data script
+        run: |
+          #!/bin/bash
+          cd /mnt
+          wget "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.94/bin/apache-tomcat-9.0.94.zip"
+          unzip apache-tomcat-9.0.94.zip
+          chmod -R 777 apache-tomcat-9.0.94
+
+          AWS_DEFAULT_REGION="ap-south-1"
+          BUCKET_NAME="deploy-mayank-mumbai"
+          OBJECT_KEY="LoginWebApp.war"
+          DESTINATION_PATH="/mnt/apache-tomcat-9.0.94/webapps"
+
+          # Configure AWS CLI
+          echo "Configuring AWS CLI"
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws configure set default.region $AWS_DEFAULT_REGION
+
+          if [ $? -ne 0 ]; then
+              echo "AWS CLI configuration failed."
+              exit 1
+          fi
+
+          echo "Downloading object from S3..."
+          aws s3 cp s3://$BUCKET_NAME/$OBJECT_KEY $DESTINATION_PATH
+
+          # Check if the download was successful
+          if [ $? -eq 0 ]; then
+              echo "Download successful."
+          else
+              echo "Download failed."
+              exit 1
+          fi
+
+          sudo apt-get install -y openjdk-11-jdk
+          cd /mnt/apache-tomcat-9.0.94/bin
+          ./startup.sh
+
 
 
 
