Update inspec-test.yml

diff --git a/.github/workflows/inspec-test.yml b/.github/workflows/inspec-test.yml
--- a/.github/workflows/inspec-test.yml
+++ b/.github/workflows/inspec-test.yml
@@ -1,23 +1,44 @@
-name: Run Inspec Tests
+name: InSpec Tests
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
+  workflow_dispatch:
 
 jobs:
   inspec:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Check Inspec Version
-        run: |
-          inspec version
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1
 
-      - name: Run Inspec tests
+      - name: Install Dependencies
         run: |
-          inspec exec ./inspec/profile/inspec.rb
+          sudo apt-get update
+          sudo apt-get install -y ruby ruby-dev build-essential
+
+      - name: Install InSpec
+        run: |
+          gem install --user-install inspec
+          echo "$HOME/.gem/ruby/3.0.0/bin" >> $GITHUB_PATH
+
+      - name: Run InSpec Tests
+        id: inspec
+        run: |
+          inspec exec public_mayank/inspec/profile/inspec.rb -t aws:// | tee inspec_output.log
+          if [ $? -ne 0 ]; then
+            echo "InSpec tests failed"
+            exit 1
+          fi
+
+      - name: Upload InSpec Results
+        uses: actions/upload-artifact@v2
+        with:
+          name: inspec-output
+          path: inspec_output.log
