Update inspec-test.yml

diff --git a/.github/workflows/inspec-test.yml b/.github/workflows/inspec-test.yml
--- a/.github/workflows/inspec-test.yml
+++ b/.github/workflows/inspec-test.yml
@@ -38,19 +38,22 @@ jobs:
       - name: Install Bundler Locally
         run: |
           gem install bundler --user-install
-          echo "Bundler Installation Path:"
-          echo $PATH
+          echo "Bundler installed. Checking paths..."
+          echo "PATH: $PATH"
           echo "GEM_HOME: $GEM_HOME"
-          echo "Adding gem binaries to PATH"
+          echo "GEM_BIN: $HOME/.gem/ruby/3.0.0/bin"
           echo "export PATH=\$PATH:\$HOME/.gem/ruby/3.0.0/bin" >> $GITHUB_ENV
+
+      - name: Verify Bundler Installation
+        run: |
           echo "Bundler Version:"
-          ~/.gem/ruby/3.0.0/bin/bundler --version || true  # Add '|| true' to prevent exit on failure
+          ~/.gem/ruby/3.0.0/bin/bundler --version || echo "Bundler not found"
 
       - name: Install InSpec via Bundler
         run: |
           echo "source 'https://rubygems.org'" > Gemfile
           echo "gem 'inspec'" >> Gemfile
-          ~/.gem/ruby/3.0.0/bin/bundle install --path vendor/bundle
+          ~/.gem/ruby/3.0.0/bin/bundle install --path vendor/bundle || echo "Bundler not found for install"
 
       - name: Run InSpec Tests
         run: |
